# 清洗规则草案 (Cleaning Rules Draft)
# Generated by: analyze/quality-audit
# Purpose: Input for Governance Skill

rules:
  - id: "R001"
    target_field: "temperature"
    action: "set_null"
    condition: "value < 0 or value > 1200"
    reason: "Physical limits exceeded (sensor failure)"

  - id: "R002"
    target_field: "pressure"
    action: "clip"
    params:
      min: 0.0
      max: 10.0
    reason: "Operational range constraint"

  - id: "R003"
    target_field: "timestamp"
    action: "drop_duplicates"
    params:
      keep: "first"
    reason: "Duplicate timestamps found"

  - id: "R004"
    target_field: "all_sensors"
    action: "ffill"
    params:
      limit: 30
    reason: "Short communication gaps (<30s)"
